version: 0.2
        
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - yarn install
  build:
    on-failure: ABORT
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: public

